"""verify_PMNS_overdetermination_2026-07-03.py

THE PMNS OVERDETERMINATION WEB (2026-07-03). The published UFFT neutrino
formula set (all frozen in Papers #35, #51, #54, #71 before this test was
conceived) is generated by the SINGLE irrational x = sqrt(Delta) with
fixed small-rational coefficients:

    tan^2(th12) = (x/9)(1 - x/144)          [#35 LO, #71 NLO]
    sin^2(th23) = 1/2 + x/81                [#35 LO, #51 NLO]
    sin(th13)   = (x/27)(1 - x/162)         [#35 LO, #51 NLO]
    |Dm2_32|/Dm2_21 = 2x^2 - 1              [#35/#54]
    (plus delta_PMNS = 3 delta_CKM, DUNE-testable, not yet measured)

Eliminating the cell integers gives THEORY-FREE observable relations:
    W1: sin^2(th13) predicted from measured tan^2(th12) alone
    W2: sin^2(th23) = 1/2 + tan^2(th12)/9
    W3: Dm^2-ratio  = 2 x(t)^2 - 1 from measured tan^2(th12) alone

RESULTS (NuFIT 5.2 NO values as quoted in the published papers):
    zero-parameter test at x = sqrt(17): chi^2 = 0.30 on 4 observables,
    all pulls <= 0.44 sigma;
    one-parameter fit: x = 4.105 (sqrt17 = 4.123), consistent;
    theory-free web: W1 -0.15 sigma, W2 +0.15 sigma, W3 +0.09 sigma.

DOF ACCOUNTING (mirrors the quark sum-rule argument, Ch. 35/36 of the
book): 4 measured observables, 1 parameter (which itself lands on the
integer discriminant), 3 redundancy checks passing sub-0.2 sigma.
Per the Match Gate graduation rule (FAILSAFES rule 4: a match graduates
by membership in an overdetermined system), the PMNS set - including
tan^2(th12), previously FAIL-standalone with 12484 rivals - GRADUATES
as an overdetermined system.

CAVEATS (for the paper version): (i) NuFIT parameters are correlated;
the pulls here treat errors as independent - redo with the NuFIT chi^2
maps; (ii) refresh to the latest NuFIT release; (iii) the fifth check
(delta_PMNS = 3 delta_CKM) awaits DUNE; (iv) a gate-2.0 rival count for
one-parameter rational webs is the right sharpening of the statistics.

Run: python verify_PMNS_overdetermination_2026-07-03.py  (numpy/scipy, ~1 s)
"""
import numpy as np, sys
from scipy.optimize import minimize_scalar, brentq

FAILED=[]
def check(name,ok,detail=""):
    print(("PASS  " if ok else "FAIL  ")+name+(("   "+detail) if detail else ""))
    if not ok: FAILED.append(name)

obs = {
 'tan2th12': (0.443, 0.027),
 'sin2th23': (0.546, 0.021),
 'sin2th13': (0.02203, 0.00056),
 'Rm':       (32.6, 0.9),
}
def preds(x):
    return {'tan2th12':(x/9)*(1-x/144),
            'sin2th23':0.5+x/81,
            'sin2th13':((x/27)*(1-x/162))**2,
            'Rm':2*x*x-1}
def chi2(x):
    p=preds(x)
    return sum(((p[k]-v)/e)**2 for k,(v,e) in obs.items())

x17=np.sqrt(17)
c0=chi2(x17)
check("zero-parameter test: chi^2(x=sqrt17) < 1 on 4 observables",
      c0<1.0, f"chi2={c0:.3f}")
p=preds(x17)
pulls={k:(p[k]-v)/e for k,(v,e) in obs.items()}
check("all pulls at x=sqrt17 below 0.5 sigma",
      all(abs(u)<0.5 for u in pulls.values()),
      "; ".join(f"{k} {u:+.2f}" for k,u in pulls.items()))
res=minimize_scalar(chi2,bounds=(3.0,5.0),method='bounded')
check("one-parameter fit consistent with sqrt(17)",
      abs(res.x-x17)<0.05, f"x_fit={res.x:.4f}")
t,te=obs['tan2th12']
x_t=brentq(lambda x:(x/9)*(1-x/144)-t,3,5)
w1=((x_t/27)*(1-x_t/162))**2
w2=0.5+t/9
w3=2*x_t**2-1
check("W1 theory-free: sin^2(th13) from tan^2(th12) alone within 0.5 sigma",
      abs((w1-obs['sin2th13'][0])/obs['sin2th13'][1])<0.5,
      f"pred {w1:.5f} pull {(w1-obs['sin2th13'][0])/obs['sin2th13'][1]:+.2f}")
check("W2 theory-free: sin^2(th23) = 1/2 + tan^2(th12)/9 within 0.5 sigma",
      abs((w2-obs['sin2th23'][0])/np.hypot(te/9,obs['sin2th23'][1]))<0.5,
      f"pred {w2:.4f}")
check("W3 theory-free: mass ratio from tan^2(th12) alone within 0.5 sigma",
      abs((w3-obs['Rm'][0])/obs['Rm'][1])<0.5, f"pred {w3:.2f}")
# structural identities (exact, symbolic-level)
import sympy as sp
S=sp.sqrt(17)
r1,r2=(9-S)/2,(9+S)/2
check("structural: tan2th12 LO = (r2-r1)/(r1+r2)",
      sp.simplify((r2-r1)/(r1+r2)-S/9)==0)
check("structural: eps = (r2-r1)/(r1+r2)^2 = sqrt17/81",
      sp.simplify((r2-r1)/(r1+r2)**2-S/81)==0)
check("structural: Rm = 2*Delta-1 = (r1-1)^2+(r2-1)^2",
      sp.simplify((r1-1)**2+(r2-1)**2-33)==0)
print()
if FAILED: print("OPEN:",FAILED); sys.exit(1)
print("PMNS OVERDETERMINATION VERIFIED - tan^2(th12) and the PMNS set "
      "graduate per the Match Gate rule (see caveats in docstring)")
