"""verify_ml3_chirality_2026-07-03.py

ML3 step 1 (the chiral second-quantised vacuum; the A1-Weinberg odd part and
the Paper #59 emergence-bridge chiral-fermion problem are the same object).
Companion: .explorations/UFFT_Explorations_2026-07-03.md Section 9.

RESULT (the run's finding): the foam's chirality is NOT band-topological.
Single-particle topology is provably trivial for the T1u sector, so no
single-particle construction can supply the chiral asymmetry. This is the
geometric root of the whole P4-P14 obstruction chain and it localises ML3
definitively to interacting many-body physics.

  H1  The chirality operator is the inter-type torsion: on the (sq,hx)
      polarization doublet, T = P_sq L P_hx - P_hx L P_sq = -2i sigma_y
      (real antisymmetric [[0,-2],[2,0]]), so C = T/2i = -sigma_y is the
      Hermitian chirality. sigma_y is the ONLY pseudospin direction the
      real Bloch Hamiltonian leaves empty.

  H2  The single-polarization T1u Bloch block is REAL (d_y(k) = 0
      identically) and GAPPED (min sqrt(d_x^2+d_z^2) > 2 over the BZ): no
      Dirac/Weyl points. A real Hamiltonian has identically zero Berry
      curvature -> vector-like couplings (the geometric form of P9/P10/P14).

  H3  No single-particle torsion term makes it chiral. Adding a uniform
      chirality mass m*sigma_y keeps Chern = 0 exactly (symmetry-protected).
      Adding a Wilson k-dependent torsion m0*sum(1-cos k)*sigma_y also keeps
      Chern = 0: the local curvature it generates cancels in +- pairs
      (Nielsen-Ninomiya). Single-particle band topology is ruled out.

CONCLUSION: the foam T1u chirality cannot come from single-particle band
topology (Chern == 0 for every single-particle torsion term, N-N-protected).
It must be interaction-driven. ML3 is thereby sharpened from "some chiral
filling" to a concrete order parameter: a spontaneous inter-type torsion
condensate <T> != 0 generated by many-body dynamics (TR-odd, Galois-root-
selecting). Whether foam dynamics generates it, and whether its magnitude
gives C_A sqrt(Delta), is the open problem.

Run: python verify_ml3_chirality_2026-07-03.py  (~30 s)
"""
import itertools, sys
import numpy as np

FAILED=[]
def check(n,ok,d=""):
    print(("PASS  " if ok else "FAIL  ")+n+(("   "+d) if d else ""))
    if not ok: FAILED.append(n)

sq=[(1,0,0),(-1,0,0),(0,1,0),(0,-1,0),(0,0,1),(0,0,-1)]
hx=list(itertools.product([1,-1],repeat=3)); F=14
Ad=np.zeros((F,F),int)
for hi_,h in enumerate(hx):
    hi=6+hi_
    for ax,s in enumerate(h):
        d=[0,0,0]; d[ax]=s; Ad[hi,sq.index(tuple(d))]=Ad[sq.index(tuple(d)),hi]=1
    for hj_,h2 in enumerate(hx):
        if hi_<hj_ and sum(a!=b for a,b in zip(h,h2))==1: Ad[hi,6+hj_]=Ad[6+hj_,hi]=1
L=np.diag(Ad.sum(1))-Ad
def fbar(i):
    if i<6: return sq.index(tuple(-x for x in sq[i]))
    return 6+hx.index(tuple(-x for x in hx[i-6]))
amat=np.array([[2,2,-2],[-2,2,2],[2,-2,2]],float)
Rv=np.zeros((F,3))
for i in range(6): Rv[i]=4*np.array(sq[i])
for i,h in enumerate(hx): Rv[6+i]=2*np.array(h)
Rrow=np.array([np.linalg.solve(amat.T,Rv[f]) for f in range(F)])
es=np.exp(-2*np.sqrt(2)); eh=np.exp(-np.sqrt(6)); sy=np.array([[0,-1j],[1j,0]])
T=np.diag([1.]*6+[0.]*8)@L@np.diag([0.]*6+[1.]*8)-np.diag([0.]*6+[1.]*8)@L@np.diag([1.]*6+[0.]*8)
def Hk(kv):
    ee=np.array([es]*6+[eh]*8); X=np.zeros((F,F),complex)
    for f in range(F): X[f,fbar(f)]=ee[f]*np.exp(1j*np.dot(kv,Rrow[f]))
    return L.astype(complex)+np.diag(ee)-X
a0=np.zeros(F); b0=np.zeros(F)
for i,dd in enumerate(sq): a0[i]=dd[0]
for i,h in enumerate(hx): b0[6+i]=h[0]
B=np.stack([a0/np.linalg.norm(a0),b0/np.linalg.norm(b0)],1).astype(complex)

# H1
Tblk=B.conj().T@T@B
check("H1 inter-type torsion on doublet = -2i sigma_y; C=T/2i=-sigma_y",
      np.allclose(Tblk,-2j*sy))
# H2
mn=1e9; mxdy=0.0; rng=np.random.default_rng(1)
for _ in range(3000):
    kv=rng.uniform(-np.pi,np.pi,3); blk=B.conj().T@Hk(kv)@B
    mxdy=max(mxdy,abs(-np.imag(blk[0,1])))
    mn=min(mn,np.hypot(np.real(blk[0,1]),0.5*np.real(blk[0,0]-blk[1,1])))
check("H2 block real (d_y=0) and gapped (min|d|>2): no Dirac pts, zero "
      "Berry curvature", mxdy<1e-12 and mn>2.0, f"min|d|={mn:.3f}")
# H3
def low(kk,m,wil):
    mk=m*sum(1-np.cos(kk[a]) for a in range(3)) if wil else m
    w,v=np.linalg.eigh(B.conj().T@Hk(kk)@B+mk*sy); return v[:,0]
def curv(k,m,wil,h=2e-3):
    k10=k.copy();k10[1]+=h;k11=k.copy();k11[1]+=h;k11[2]+=h;k01=k.copy();k01[2]+=h
    u=[low(x,m,wil) for x in (k,k10,k11,k01)]
    return np.angle(np.vdot(u[0],u[1])*np.vdot(u[1],u[2])*np.vdot(u[2],u[3])*np.vdot(u[3],u[0]))
ks=np.linspace(-np.pi,np.pi,50,endpoint=False)
def chern(m,wil):
    t=0.0
    for ku in ks:
        for kw in ks: t+=curv(np.array([0.0,ku,kw]),m,wil)
    return t/(2*np.pi)
cu=[abs(chern(m,False)) for m in (0.5,1.0,2.0)]
cw=[abs(chern(m,True)) for m in (0.5,1.0,2.0)]
check("H3 Chern=0 for uniform torsion mass (all m): single-particle "
      "topology trivial", max(cu)<1e-6, f"|Chern|max={max(cu):.1e}")
check("H3 Chern=0 for Wilson k-dependent torsion (all m0): curvature "
      "cancels in +-pairs (Nielsen-Ninomiya)", max(cw)<1e-6,
      f"|Chern|max={max(cw):.1e}")

print()
if FAILED: print("OPEN/FAIL:",FAILED); sys.exit(1)
print("ML3: single-particle band topology RULED OUT (Chern=0, N-N-protected); "
      "chirality is necessarily interaction-driven; order parameter = <T>")
