import FaceGraph.Theorem31

/-!
# The face-graph Laplacian spectra of the other four Fedorov parallelohedra (Table 2, Appendix A)

Each graph is defined by its adjacency rule (Section 7 of the note), the Laplacian is built from the rule, proved
equal to a literal matrix by `decide +kernel`, and the characteristic polynomial is obtained exactly as in
`Theorem31.lean`: a rational change of basis to 2 × 2 blocks (diagonal blocks for the rational eigenvalues, the
cyclic pair `(v, L v)` for the irreducible quadratic `x² - 10x + 20` of the elongated dodecahedron), the block
identity decided by the kernel, and the polynomial assembled from the blocks. The change-of-basis matrices were
generated by `gen_fedorov.py` and are checked here, not trusted.

Conventions. Cube: faces 0–5 are `+x, -x, +y, -y, +z, -z` (pair `v / 2`); two faces are adjacent unless opposite
(`K_{2,2,2}`). Hexagonal prism: faces 0–5 the squares in cyclic order, 6–7 the hexagons; squares adjacent when
consecutive, every square adjacent to both hexagons, the hexagons not adjacent (`C₆ ∨ K̄₂`). Rhombic dodecahedron:
face `k` (0–11) is the cube edge with axis `k / 4` from the vertex whose other two bits are `k % 4`; two faces are
adjacent when the edges share a vertex (the line graph of the cube). Elongated dodecahedron: faces `0–3` the
hexagons `H_i`, `4–7` the top rhombi `T_i`, `8–11` the bottom rhombi `B_i`, `i ∈ ℤ/4`; each class is a 4-cycle and
`H_i` is adjacent to `T_i, T_{i+1}, B_i, B_{i+1}`.
-/

open Matrix Polynomial

/-- Laplacian of a graph on `Fin n` given by a symmetric adjacency rule. -/
def lapOf {n : ℕ} (adj : ℕ → ℕ → Bool) : Matrix (Fin n) (Fin n) ℚ := fun v w =>
  if v = w then (((List.range n).filter (fun u => adj v.val u)).length : ℚ) else if adj v.val w.val then -1 else 0

/-- `(i, k) ↦ i + 2k`, as `e72` in `Theorem31.lean`. -/
def e23 : Fin 2 × Fin 3 ≃ Fin 6 := (Equiv.prodComm (Fin 2) (Fin 3)).trans finProdFinEquiv
def e24 : Fin 2 × Fin 4 ≃ Fin 8 := (Equiv.prodComm (Fin 2) (Fin 4)).trans finProdFinEquiv
def e26 : Fin 2 × Fin 6 ≃ Fin 12 := (Equiv.prodComm (Fin 2) (Fin 6)).trans finProdFinEquiv

section Cube
/-- Cube: adjacent unless opposite. -/
def cubeAdj (i j : ℕ) : Bool := i / 2 ≠ j / 2
def LcubeG : Matrix (Fin 6) (Fin 6) ℚ := lapOf cubeAdj
end Cube

section Prism
/-- Hexagonal prism: squares 0–5 in a 6-cycle, hexagons 6–7 joined to every square. -/
def prismAdj (i j : ℕ) : Bool :=
  if i < 6 ∧ j < 6 then (i + 1) % 6 = j ∨ (j + 1) % 6 = i else (i < 6 ∧ 6 ≤ j) ∨ (6 ≤ i ∧ j < 6)
def LprismG : Matrix (Fin 8) (Fin 8) ℚ := lapOf prismAdj
end Prism

section Rhombic
/-- Endpoints of cube edge `k`: axis `k / 4`, the other two bits from `k % 4`. -/
def edgeEnds (k : ℕ) : ℕ × ℕ :=
  let a := k / 4
  let r := k % 4
  let b := if a = 0 then 1 else 0
  let c := if a = 2 then 1 else 2
  let u := (r % 2) * 2 ^ b + (r / 2) * 2 ^ c
  (u, u + 2 ^ a)
/-- Rhombic dodecahedron: distinct cube edges sharing a vertex (line graph of the cube). -/
def rhombicAdj (i j : ℕ) : Bool :=
  i ≠ j ∧ ((edgeEnds i).1 = (edgeEnds j).1 ∨ (edgeEnds i).1 = (edgeEnds j).2 ∨
           (edgeEnds i).2 = (edgeEnds j).1 ∨ (edgeEnds i).2 = (edgeEnds j).2)
def LrhombicG : Matrix (Fin 12) (Fin 12) ℚ := lapOf rhombicAdj
end Rhombic

section Elong
/-- Elongated dodecahedron: `H_i = i`, `T_i = 4 + i`, `B_i = 8 + i`. -/
def elongAdj (i j : ℕ) : Bool :=
  let ci := i / 4
  let cj := j / 4
  let a := i % 4
  let b := j % 4
  if ci = cj then (a + 1) % 4 = b ∨ (b + 1) % 4 = a
  else if ci = 0 then b = a ∨ b = (a + 1) % 4
  else if cj = 0 then a = b ∨ a = (b + 1) % 4
  else false
def LelongG : Matrix (Fin 12) (Fin 12) ℚ := lapOf elongAdj
end Elong


section CubeProof

def LCube : Matrix (Fin 6) (Fin 6) ℚ :=
  !![4, 0, -1, -1, -1, -1;
     0, 4, -1, -1, -1, -1;
     -1, -1, 4, 0, -1, -1;
     -1, -1, 0, 4, -1, -1;
     -1, -1, -1, -1, 4, 0;
     -1, -1, -1, -1, 0, 4]
def PCube : Matrix (Fin 6) (Fin 6) ℚ :=
  !![1, -1, -1, -1, 0, 0;
     1, -1, -1, 1, 0, 0;
     1, 1, 0, 0, -1, 0;
     1, 1, 0, 0, 1, 0;
     1, 0, 1, 0, 0, -1;
     1, 0, 1, 0, 0, 1]
def QCube : Matrix (Fin 6) (Fin 6) ℚ :=
  !![1/6, 1/6, 1/6, 1/6, 1/6, 1/6;
     -1/6, -1/6, 1/3, 1/3, -1/6, -1/6;
     -1/6, -1/6, -1/6, -1/6, 1/3, 1/3;
     -1/2, 1/2, 0, 0, 0, 0;
     0, 0, -1/2, 1/2, 0, 0;
     0, 0, 0, 0, -1/2, 1/2]
def blkCube : Fin 3 → Matrix (Fin 2) (Fin 2) ℚ :=
  ![!![0, 0; 0, 6], !![6, 0; 0, 4], !![4, 0; 0, 4]]
set_option linter.style.longLine false in
def BCube : Matrix (Fin 6) (Fin 6) ℚ := Matrix.reindex e23 e23 (Matrix.blockDiagonal blkCube)

/-- The rule-built Laplacian is the literal. -/
theorem LCubeG_eq : LcubeG = LCube := by decide +kernel
lemma LPCube : LCube * PCube = PCube * BCube := by rw [← Matrix.mulᵣ_eq, ← Matrix.mulᵣ_eq]; decide +kernel
lemma PQCube : PCube * QCube = 1 := by rw [← Matrix.mulᵣ_eq]; decide +kernel
lemma QPCube : QCube * PCube = 1 := by rw [← Matrix.mulᵣ_eq]; decide +kernel
def PunitCube : (Matrix (Fin 6) (Fin 6) ℚ)ˣ := ⟨PCube, QCube, PQCube, QPCube⟩
lemma LCube_conj : LCube = PCube * BCube * QCube := by
  calc LCube = LCube * (PCube * QCube) := by rw [PQCube, mul_one]
    _ = (LCube * PCube) * QCube := by rw [mul_assoc]
    _ = PCube * BCube * QCube := by rw [LPCube]
lemma blkCube0 : (blkCube 0).charpoly = X * (X - 6) := by
  rw [show blkCube 0 = !![0, 0; 0, 6] from rfl, cp2]; simp [Polynomial.C_ofNat]; try ring
lemma blkCube1 : (blkCube 1).charpoly = (X - 6) * (X - 4) := by
  rw [show blkCube 1 = !![6, 0; 0, 4] from rfl, cp2]; simp [Polynomial.C_ofNat]; try ring
lemma blkCube2 : (blkCube 2).charpoly = (X - 4) ^ 2 := by
  rw [show blkCube 2 = !![4, 0; 0, 4] from rfl, cp2]; simp [Polynomial.C_ofNat]; try ring
theorem charpoly_BCube : BCube.charpoly = X * (X - 6) ^ 2 * (X - 4) ^ 3 := by
  unfold BCube
  rw [Matrix.charpoly_reindex, charpoly_blockDiagonal, Fin.prod_univ_three,
    blkCube0, blkCube1, blkCube2]
  try ring
theorem charpoly_LCube : LCube.charpoly = X * (X - 6) ^ 2 * (X - 4) ^ 3 := by
  rw [LCube_conj, ← charpoly_BCube]
  have h := Matrix.charpoly_units_conj PunitCube BCube
  rw [← Matrix.coe_units_inv] at h
  exact h
/-- Table 2 row for the cube, for the rule-built Laplacian. -/
theorem charpoly_LcubeG : LcubeG.charpoly = X * (X - 6) ^ 2 * (X - 4) ^ 3 := by
  rw [LCubeG_eq]; exact charpoly_LCube
end CubeProof


section PrismProof

def LPrism : Matrix (Fin 8) (Fin 8) ℚ :=
  !![4, -1, 0, 0, 0, -1, -1, -1;
     -1, 4, -1, 0, 0, 0, -1, -1;
     0, -1, 4, -1, 0, 0, -1, -1;
     0, 0, -1, 4, -1, 0, -1, -1;
     0, 0, 0, -1, 4, -1, -1, -1;
     -1, 0, 0, 0, -1, 4, -1, -1;
     -1, -1, -1, -1, -1, -1, 6, 0;
     -1, -1, -1, -1, -1, -1, 0, 6]
def PPrism : Matrix (Fin 8) (Fin 8) ℚ :=
  !![-1, 1, -1, 0, -1, -1, -1, 1;
     -1, 1, 1, 0, 1, 0, -1, 0;
     -1, 1, -1, 0, 0, 1, 0, -1;
     -1, 1, 1, 0, -1, -1, 1, -1;
     -1, 1, -1, 0, 1, 0, 1, 0;
     -1, 1, 1, 0, 0, 1, 0, 1;
     3, 1, 0, -1, 0, 0, 0, 0;
     3, 1, 0, 1, 0, 0, 0, 0]
def QPrism : Matrix (Fin 8) (Fin 8) ℚ :=
  !![-1/24, -1/24, -1/24, -1/24, -1/24, -1/24, 1/8, 1/8;
     1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8;
     -1/6, 1/6, -1/6, 1/6, -1/6, 1/6, 0, 0;
     0, 0, 0, 0, 0, 0, -1/2, 1/2;
     -1/6, 1/3, -1/6, -1/6, 1/3, -1/6, 0, 0;
     -1/6, -1/6, 1/3, -1/6, -1/6, 1/3, 0, 0;
     -1/6, -1/3, -1/6, 1/6, 1/3, 1/6, 0, 0;
     1/6, -1/6, -1/3, -1/6, 1/6, 1/3, 0, 0]
def blkPrism : Fin 4 → Matrix (Fin 2) (Fin 2) ℚ :=
  ![!![8, 0; 0, 0], !![6, 0; 0, 6], !![5, 0; 0, 5], !![3, 0; 0, 3]]
set_option linter.style.longLine false in
def BPrism : Matrix (Fin 8) (Fin 8) ℚ := Matrix.reindex e24 e24 (Matrix.blockDiagonal blkPrism)

/-- The rule-built Laplacian is the literal. -/
theorem LPrismG_eq : LprismG = LPrism := by decide +kernel
lemma LPPrism : LPrism * PPrism = PPrism * BPrism := by rw [← Matrix.mulᵣ_eq, ← Matrix.mulᵣ_eq]; decide +kernel
lemma PQPrism : PPrism * QPrism = 1 := by rw [← Matrix.mulᵣ_eq]; decide +kernel
lemma QPPrism : QPrism * PPrism = 1 := by rw [← Matrix.mulᵣ_eq]; decide +kernel
def PunitPrism : (Matrix (Fin 8) (Fin 8) ℚ)ˣ := ⟨PPrism, QPrism, PQPrism, QPPrism⟩
lemma LPrism_conj : LPrism = PPrism * BPrism * QPrism := by
  calc LPrism = LPrism * (PPrism * QPrism) := by rw [PQPrism, mul_one]
    _ = (LPrism * PPrism) * QPrism := by rw [mul_assoc]
    _ = PPrism * BPrism * QPrism := by rw [LPPrism]
lemma blkPrism0 : (blkPrism 0).charpoly = X * (X - 8) := by
  rw [show blkPrism 0 = !![8, 0; 0, 0] from rfl, cp2]; simp [Polynomial.C_ofNat]; try ring
lemma blkPrism1 : (blkPrism 1).charpoly = (X - 6) ^ 2 := by
  rw [show blkPrism 1 = !![6, 0; 0, 6] from rfl, cp2]; simp [Polynomial.C_ofNat]; try ring
lemma blkPrism2 : (blkPrism 2).charpoly = (X - 5) ^ 2 := by
  rw [show blkPrism 2 = !![5, 0; 0, 5] from rfl, cp2]; simp [Polynomial.C_ofNat]; try ring
lemma blkPrism3 : (blkPrism 3).charpoly = (X - 3) ^ 2 := by
  rw [show blkPrism 3 = !![3, 0; 0, 3] from rfl, cp2]; simp [Polynomial.C_ofNat]; try ring
theorem charpoly_BPrism : BPrism.charpoly = X * (X - 8) * (X - 6) ^ 2 * (X - 5) ^ 2 * (X - 3) ^ 2 := by
  unfold BPrism
  rw [Matrix.charpoly_reindex, charpoly_blockDiagonal, Fin.prod_univ_four,
    blkPrism0, blkPrism1, blkPrism2, blkPrism3]
  try ring
theorem charpoly_LPrism : LPrism.charpoly = X * (X - 8) * (X - 6) ^ 2 * (X - 5) ^ 2 * (X - 3) ^ 2 := by
  rw [LPrism_conj, ← charpoly_BPrism]
  have h := Matrix.charpoly_units_conj PunitPrism BPrism
  rw [← Matrix.coe_units_inv] at h
  exact h
/-- Table 2 row for the prism, for the rule-built Laplacian. -/
theorem charpoly_LprismG : LprismG.charpoly = X * (X - 8) * (X - 6) ^ 2 * (X - 5) ^ 2 * (X - 3) ^ 2 := by
  rw [LPrismG_eq]; exact charpoly_LPrism
end PrismProof


section RhombicProof

def LRhombic : Matrix (Fin 12) (Fin 12) ℚ :=
  !![4, 0, 0, 0, -1, -1, 0, 0, -1, -1, 0, 0;
     0, 4, 0, 0, -1, -1, 0, 0, 0, 0, -1, -1;
     0, 0, 4, 0, 0, 0, -1, -1, -1, -1, 0, 0;
     0, 0, 0, 4, 0, 0, -1, -1, 0, 0, -1, -1;
     -1, -1, 0, 0, 4, 0, 0, 0, -1, 0, -1, 0;
     -1, -1, 0, 0, 0, 4, 0, 0, 0, -1, 0, -1;
     0, 0, -1, -1, 0, 0, 4, 0, -1, 0, -1, 0;
     0, 0, -1, -1, 0, 0, 0, 4, 0, -1, 0, -1;
     -1, 0, -1, 0, -1, 0, -1, 0, 4, 0, 0, 0;
     -1, 0, -1, 0, 0, -1, 0, -1, 0, 4, 0, 0;
     0, -1, 0, -1, -1, 0, -1, 0, 0, 0, 4, 0;
     0, -1, 0, -1, 0, -1, 0, -1, 0, 0, 0, 4]
def PRhombic : Matrix (Fin 12) (Fin 12) ℚ :=
  !![1, 1, 0, 0, -1, -1, 0, -1, 0, -1, 0, 0;
     1, -1, 0, 0, -1, 0, 1, -1, 0, 0, 0, -1;
     1, -1, 0, 0, 1, 0, -1, 0, -1, -1, 0, 0;
     1, 1, 0, 0, 1, 1, 0, 0, -1, 0, 0, -1;
     1, 0, 1, 0, -1, 0, 0, 1, 0, 0, -1, 1;
     1, 0, -1, 0, -1, -1, 1, 1, 0, 0, 0, 0;
     1, 0, -1, 0, 1, 1, -1, 0, 1, 0, -1, 1;
     1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0;
     1, 0, 0, 1, 0, 0, -1, 0, 0, 1, 1, -1;
     1, 0, 0, -1, 0, -1, 0, 0, 0, 1, 0, 0;
     1, 0, 0, -1, 0, 1, 0, 0, 0, 0, 1, 0;
     1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1]
def QRhombic : Matrix (Fin 12) (Fin 12) ℚ :=
  !![1/12, 1/12, 1/12, 1/12, 1/12, 1/12, 1/12, 1/12, 1/12, 1/12, 1/12, 1/12;
     1/4, -1/4, -1/4, 1/4, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 0, 0, 0, 1/4, -1/4, -1/4, 1/4, 0, 0, 0, 0;
     0, 0, 0, 0, 0, 0, 0, 0, 1/4, -1/4, -1/4, 1/4;
     -1/8, -1/8, 1/8, 1/8, -1/4, 0, 0, 1/4, -1/8, 1/8, -1/8, 1/8;
     -1/8, 1/8, -1/8, 1/8, 1/8, -1/8, 1/8, -1/8, 0, -1/4, 1/4, 0;
     -1/8, 1/8, -1/8, 1/8, -1/8, 1/8, -1/8, 1/8, -1/4, 0, 0, 1/4;
     -5/24, -5/24, 1/24, 1/24, 1/6, 5/12, -1/12, 1/6, 1/24, -5/24, 1/24, -5/24;
     1/24, 1/24, -5/24, -5/24, -1/12, 1/6, 1/6, 5/12, 1/24, -5/24, 1/24, -5/24;
     -5/24, 1/24, -5/24, 1/24, 1/24, -5/24, 1/24, -5/24, 1/6, 5/12, -1/12, 1/6;
     1/24, -5/24, 1/24, -5/24, -5/24, 1/24, -5/24, 1/24, 1/6, -1/12, 5/12, 1/6;
     1/24, -5/24, 1/24, -5/24, 1/24, -5/24, 1/24, -5/24, -1/12, 1/6, 1/6, 5/12]
def blkRhombic : Fin 6 → Matrix (Fin 2) (Fin 2) ℚ :=
  ![!![0, 0; 0, 4], !![4, 0; 0, 4], !![2, 0; 0, 2], !![2, 0; 0, 6], !![6, 0; 0, 6], !![6, 0; 0, 6]]
set_option linter.style.longLine false in
def BRhombic : Matrix (Fin 12) (Fin 12) ℚ := Matrix.reindex e26 e26 (Matrix.blockDiagonal blkRhombic)

/-- The rule-built Laplacian is the literal. -/
theorem LRhombicG_eq : LrhombicG = LRhombic := by decide +kernel
lemma LPRhombic : LRhombic * PRhombic = PRhombic * BRhombic := by rw [← Matrix.mulᵣ_eq, ← Matrix.mulᵣ_eq]; decide +kernel
lemma PQRhombic : PRhombic * QRhombic = 1 := by rw [← Matrix.mulᵣ_eq]; decide +kernel
lemma QPRhombic : QRhombic * PRhombic = 1 := by rw [← Matrix.mulᵣ_eq]; decide +kernel
def PunitRhombic : (Matrix (Fin 12) (Fin 12) ℚ)ˣ := ⟨PRhombic, QRhombic, PQRhombic, QPRhombic⟩
lemma LRhombic_conj : LRhombic = PRhombic * BRhombic * QRhombic := by
  calc LRhombic = LRhombic * (PRhombic * QRhombic) := by rw [PQRhombic, mul_one]
    _ = (LRhombic * PRhombic) * QRhombic := by rw [mul_assoc]
    _ = PRhombic * BRhombic * QRhombic := by rw [LPRhombic]
lemma blkRhombic0 : (blkRhombic 0).charpoly = X * (X - 4) := by
  rw [show blkRhombic 0 = !![0, 0; 0, 4] from rfl, cp2]; simp [Polynomial.C_ofNat]; try ring
lemma blkRhombic1 : (blkRhombic 1).charpoly = (X - 4) ^ 2 := by
  rw [show blkRhombic 1 = !![4, 0; 0, 4] from rfl, cp2]; simp [Polynomial.C_ofNat]; try ring
lemma blkRhombic2 : (blkRhombic 2).charpoly = (X - 2) ^ 2 := by
  rw [show blkRhombic 2 = !![2, 0; 0, 2] from rfl, cp2]; simp [Polynomial.C_ofNat]; try ring
lemma blkRhombic3 : (blkRhombic 3).charpoly = (X - 6) * (X - 2) := by
  rw [show blkRhombic 3 = !![2, 0; 0, 6] from rfl, cp2]; simp [Polynomial.C_ofNat]; try ring
lemma blkRhombic4 : (blkRhombic 4).charpoly = (X - 6) ^ 2 := by
  rw [show blkRhombic 4 = !![6, 0; 0, 6] from rfl, cp2]; simp [Polynomial.C_ofNat]; try ring
lemma blkRhombic5 : (blkRhombic 5).charpoly = (X - 6) ^ 2 := by
  rw [show blkRhombic 5 = !![6, 0; 0, 6] from rfl, cp2]; simp [Polynomial.C_ofNat]; try ring
theorem charpoly_BRhombic : BRhombic.charpoly = X * (X - 6) ^ 5 * (X - 4) ^ 3 * (X - 2) ^ 3 := by
  unfold BRhombic
  rw [Matrix.charpoly_reindex, charpoly_blockDiagonal, Fin.prod_univ_six,
    blkRhombic0, blkRhombic1, blkRhombic2, blkRhombic3, blkRhombic4, blkRhombic5]
  try ring
theorem charpoly_LRhombic : LRhombic.charpoly = X * (X - 6) ^ 5 * (X - 4) ^ 3 * (X - 2) ^ 3 := by
  rw [LRhombic_conj, ← charpoly_BRhombic]
  have h := Matrix.charpoly_units_conj PunitRhombic BRhombic
  rw [← Matrix.coe_units_inv] at h
  exact h
/-- Table 2 row for the rhombic, for the rule-built Laplacian. -/
theorem charpoly_LrhombicG : LrhombicG.charpoly = X * (X - 6) ^ 5 * (X - 4) ^ 3 * (X - 2) ^ 3 := by
  rw [LRhombicG_eq]; exact charpoly_LRhombic
end RhombicProof


section ElongProof

def LElong : Matrix (Fin 12) (Fin 12) ℚ :=
  !![6, -1, 0, -1, -1, -1, 0, 0, -1, -1, 0, 0;
     -1, 6, -1, 0, 0, -1, -1, 0, 0, -1, -1, 0;
     0, -1, 6, -1, 0, 0, -1, -1, 0, 0, -1, -1;
     -1, 0, -1, 6, -1, 0, 0, -1, -1, 0, 0, -1;
     -1, 0, 0, -1, 4, -1, 0, -1, 0, 0, 0, 0;
     -1, -1, 0, 0, -1, 4, -1, 0, 0, 0, 0, 0;
     0, -1, -1, 0, 0, -1, 4, -1, 0, 0, 0, 0;
     0, 0, -1, -1, -1, 0, -1, 4, 0, 0, 0, 0;
     -1, 0, 0, -1, 0, 0, 0, 0, 4, -1, 0, -1;
     -1, -1, 0, 0, 0, 0, 0, 0, -1, 4, -1, 0;
     0, -1, -1, 0, 0, 0, 0, 0, 0, -1, 4, -1;
     0, 0, -1, -1, 0, 0, 0, 0, -1, 0, -1, 4]
def PElong : Matrix (Fin 12) (Fin 12) ℚ :=
  !![-1, -6, 0, 0, -1, 0, 1, 0, 0, 0, -1, -1;
     0, 0, -1, -6, 1, 0, 1, 0, 0, 0, -1, -1;
     1, 6, 0, 0, -1, 0, 1, 0, 0, 0, -1, -1;
     0, 0, 1, 6, 1, 0, 1, 0, 0, 0, -1, -1;
     0, 1, 0, -1, 0, -1, 1, 1, 0, -1, 1, 1;
     0, 1, 0, 1, 0, -1, 1, 0, 1, 1, 0, 0;
     0, -1, 0, 1, 0, -1, 1, -1, 0, -1, 1, 1;
     0, -1, 0, -1, 0, -1, 1, 0, -1, 1, 0, 0;
     0, 1, 0, -1, 0, 1, 1, -1, 0, 0, 1, 0;
     0, 1, 0, 1, 0, 1, 1, 0, -1, 0, 0, 1;
     0, -1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0;
     0, -1, 0, -1, 0, 1, 1, 0, 1, 0, 0, 1]
def QElong : Matrix (Fin 12) (Fin 12) ℚ :=
  !![-1/2, 0, 1/2, 0, -3/4, -3/4, 3/4, 3/4, -3/4, -3/4, 3/4, 3/4;
     0, 0, 0, 0, 1/8, 1/8, -1/8, -1/8, 1/8, 1/8, -1/8, -1/8;
     0, -1/2, 0, 1/2, 3/4, -3/4, -3/4, 3/4, 3/4, -3/4, -3/4, 3/4;
     0, 0, 0, 0, -1/8, 1/8, 1/8, -1/8, -1/8, 1/8, 1/8, -1/8;
     -1/4, 1/4, -1/4, 1/4, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 0, 0, 0, -1/8, -1/8, -1/8, -1/8, 1/8, 1/8, 1/8, 1/8;
     1/12, 1/12, 1/12, 1/12, 1/12, 1/12, 1/12, 1/12, 1/12, 1/12, 1/12, 1/12;
     0, 0, 0, 0, 1/4, 0, -1/4, 0, -1/4, 0, 1/4, 0;
     0, 0, 0, 0, 0, 1/4, 0, -1/4, 0, -1/4, 0, 1/4;
     -1/12, -1/12, -1/12, -1/12, -5/24, 7/24, -5/24, 7/24, 1/24, 1/24, 1/24, 1/24;
     -1/12, -1/12, -1/12, -1/12, 1/24, 1/24, 1/24, 1/24, 7/24, -5/24, 7/24, -5/24;
     -1/12, -1/12, -1/12, -1/12, 1/24, 1/24, 1/24, 1/24, -5/24, 7/24, -5/24, 7/24]
def blkElong : Fin 6 → Matrix (Fin 2) (Fin 2) ℚ :=
  ![!![0, -20; 1, 10], !![0, -20; 1, 10], !![8, 0; 0, 2], !![0, 0; 0, 4], !![4, 0; 0, 6], !![6, 0; 0, 6]]
set_option linter.style.longLine false in
def BElong : Matrix (Fin 12) (Fin 12) ℚ := Matrix.reindex e26 e26 (Matrix.blockDiagonal blkElong)

/-- The rule-built Laplacian is the literal. -/
theorem LElongG_eq : LelongG = LElong := by decide +kernel
lemma LPElong : LElong * PElong = PElong * BElong := by rw [← Matrix.mulᵣ_eq, ← Matrix.mulᵣ_eq]; decide +kernel
lemma PQElong : PElong * QElong = 1 := by rw [← Matrix.mulᵣ_eq]; decide +kernel
lemma QPElong : QElong * PElong = 1 := by rw [← Matrix.mulᵣ_eq]; decide +kernel
def PunitElong : (Matrix (Fin 12) (Fin 12) ℚ)ˣ := ⟨PElong, QElong, PQElong, QPElong⟩
lemma LElong_conj : LElong = PElong * BElong * QElong := by
  calc LElong = LElong * (PElong * QElong) := by rw [PQElong, mul_one]
    _ = (LElong * PElong) * QElong := by rw [mul_assoc]
    _ = PElong * BElong * QElong := by rw [LPElong]
lemma blkElong0 : (blkElong 0).charpoly = X ^ 2 - 10 * X + 20 := by
  rw [show blkElong 0 = !![0, -20; 1, 10] from rfl, cp2]; simp [Polynomial.C_ofNat]; try ring
lemma blkElong1 : (blkElong 1).charpoly = X ^ 2 - 10 * X + 20 := by
  rw [show blkElong 1 = !![0, -20; 1, 10] from rfl, cp2]; simp [Polynomial.C_ofNat]; try ring
lemma blkElong2 : (blkElong 2).charpoly = (X - 8) * (X - 2) := by
  rw [show blkElong 2 = !![8, 0; 0, 2] from rfl, cp2]; simp [Polynomial.C_ofNat]; try ring
lemma blkElong3 : (blkElong 3).charpoly = X * (X - 4) := by
  rw [show blkElong 3 = !![0, 0; 0, 4] from rfl, cp2]; simp [Polynomial.C_ofNat]; try ring
lemma blkElong4 : (blkElong 4).charpoly = (X - 6) * (X - 4) := by
  rw [show blkElong 4 = !![4, 0; 0, 6] from rfl, cp2]; simp [Polynomial.C_ofNat]; try ring
lemma blkElong5 : (blkElong 5).charpoly = (X - 6) ^ 2 := by
  rw [show blkElong 5 = !![6, 0; 0, 6] from rfl, cp2]; simp [Polynomial.C_ofNat]; try ring
theorem charpoly_BElong : BElong.charpoly = X * (X - 8) * (X - 6) ^ 3 * (X - 4) ^ 2 * (X - 2) * (X ^ 2 - 10 * X + 20) ^ 2 := by
  unfold BElong
  rw [Matrix.charpoly_reindex, charpoly_blockDiagonal, Fin.prod_univ_six,
    blkElong0, blkElong1, blkElong2, blkElong3, blkElong4, blkElong5]
  try ring
theorem charpoly_LElong : LElong.charpoly = X * (X - 8) * (X - 6) ^ 3 * (X - 4) ^ 2 * (X - 2) * (X ^ 2 - 10 * X + 20) ^ 2 := by
  rw [LElong_conj, ← charpoly_BElong]
  have h := Matrix.charpoly_units_conj PunitElong BElong
  rw [← Matrix.coe_units_inv] at h
  exact h
/-- Table 2 row for the elong, for the rule-built Laplacian. -/
theorem charpoly_LelongG : LelongG.charpoly = X * (X - 8) * (X - 6) ^ 3 * (X - 4) ^ 2 * (X - 2) * (X ^ 2 - 10 * X + 20) ^ 2 := by
  rw [LElongG_eq]; exact charpoly_LElong
end ElongProof

#print axioms charpoly_LcubeG
#print axioms charpoly_LprismG
#print axioms charpoly_LrhombicG
#print axioms charpoly_LelongG
