import FaceGraph.Theorem31
import Mathlib.NumberTheory.Zsqrtd.GaussianInt
import Mathlib.RingTheory.Localization.FractionRing

/-!
# Quarter flux (Theorem 6.4 of the note at q = 6), machine-checked over the Gaussian integers

`D6` is the magnetic Laplacian Δ₆ of the note's equation (L6) in the gauge (B): squares first (index 2a + (0 if σ = +1
else 1) for the square (a, σ)), then the eight hexagons in the order of `itertools.product([1,-1], repeat=3)`;
every off-diagonal entry is 0, ±1 or ±i. A Gaussian-integer matrix is written here as `ofRI R I` with `R`, `I` its real
and imaginary integer parts, so that every matrix identity reduces to identities between integer matrices, which the
kernel decides by evaluation (`decide +kernel` on `Matrix.mulᵣ`).

The proof follows the note's Section 6.1: the Walsh vectors χ_S of the cube, S ⊆ {1,2,3}, together with their square
partners B χ_S, span invariant planes with blocks [[4, -1], [-4, 6 - μ]] (μ = 1 for |S| = 1, μ = -1 for |S| = 2), and the
two Walsh vectors with |S| = 0, 3 are eigenvectors with eigenvalues 3 and 9. The change of basis `P6` has Gaussian-integer
entries and `Q6 = P6ᴴ` satisfies `Q6 * P6 = diag(32, 8, …)`, so `P6` is invertible over the fraction field ℚ(i); the
characteristic polynomial is compared there and pulled back by injectivity of `Polynomial.map`.
-/

open Matrix Polynomial

local notation "ℤ[i]" => GaussianInt

/-! ## Gaussian-integer matrices from integer parts -/

/-- A Gaussian-integer matrix from its real and imaginary integer parts. -/
def ofRI {m n : Type*} (A B : Matrix m n ℤ) : Matrix m n ℤ[i] := fun i j => ⟨A i j, B i j⟩

lemma Zsqrtd.re_sum {d : ℤ} {ι : Type*} (s : Finset ι) (f : ι → ℤ√d) :
    (∑ k ∈ s, f k).re = ∑ k ∈ s, (f k).re := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | insert a s ha ih => rw [Finset.sum_insert ha, Finset.sum_insert ha, Zsqrtd.re_add, ih]

lemma Zsqrtd.im_sum {d : ℤ} {ι : Type*} (s : Finset ι) (f : ι → ℤ√d) :
    (∑ k ∈ s, f k).im = ∑ k ∈ s, (f k).im := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | insert a s ha ih => rw [Finset.sum_insert ha, Finset.sum_insert ha, Zsqrtd.im_add, ih]

/-- Matrix product in terms of real and imaginary parts: (R + iI)(R' + iI') = (RR' - II') + i(RI' + IR'). -/
lemma ofRI_mul {l m n : Type*} [Fintype m] (A B : Matrix l m ℤ) (C D : Matrix m n ℤ) :
    ofRI A B * ofRI C D = ofRI (A * C - B * D) (A * D + B * C) := by
  ext i j
  · simp only [Matrix.mul_apply, ofRI, Zsqrtd.re_sum, Zsqrtd.re_mul, Matrix.sub_apply]
    rw [sub_eq_add_neg, ← Finset.sum_neg_distrib, ← Finset.sum_add_distrib]
    simp
  · simp only [Matrix.mul_apply, ofRI, Zsqrtd.im_sum, Zsqrtd.im_mul, Matrix.add_apply]
    simp [← Finset.sum_add_distrib]

lemma ofRI_zero_eq_map {m n : Type*} (A : Matrix m n ℤ) :
    ofRI A 0 = A.map (Int.castRingHom ℤ[i]) := by
  ext i j <;> simp [ofRI]

lemma ofRI_diagonal {n : Type*} [DecidableEq n] (v : n → ℤ) :
    Matrix.diagonal (fun i => ((v i : ℤ) : ℤ[i])) = ofRI (Matrix.diagonal v) 0 := by
  ext i j <;> simp [ofRI, Matrix.diagonal_apply] <;> split_ifs <;> simp

/-! ## The matrices (real and imaginary parts generated by `verify_quarter_flux` from the note's gauge (B)) -/

def D6r : Matrix (Fin 14) (Fin 14) ℤ :=
  !![4, 0, 0, 0, 0, 0, -1, 0, 0, 1, 0, 0, 0, 0;
     0, 4, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 1;
     0, 0, 4, 0, 0, 0, -1, 0, 0, 0, 0, 1, 0, 0;
     0, 0, 0, 4, 0, 0, 0, 0, -1, 0, 0, 0, 0, 1;
     0, 0, 0, 0, 4, 0, -1, 0, 0, 0, 0, 0, 1, 0;
     0, 0, 0, 0, 0, 4, 0, -1, 0, 0, 0, 0, 0, 1;
     -1, 0, -1, 0, -1, 0, 6, -1, -1, 0, -1, 0, 0, 0;
     0, 0, 0, 0, 0, -1, -1, 6, 0, -1, 0, -1, 0, 0;
     0, 0, 0, -1, 0, 0, -1, 0, 6, -1, 0, 0, -1, 0;
     1, 0, 0, 0, 0, 0, 0, -1, -1, 6, 0, 0, 0, -1;
     0, -1, 0, 0, 0, 0, -1, 0, 0, 0, 6, -1, -1, 0;
     0, 0, 1, 0, 0, 0, 0, -1, 0, 0, -1, 6, 0, -1;
     0, 0, 0, 0, 1, 0, 0, 0, -1, 0, -1, 0, 6, -1;
     0, 1, 0, 1, 0, 1, 0, 0, 0, -1, 0, -1, -1, 6]

def D6i : Matrix (Fin 14) (Fin 14) ℤ :=
  !![0, 0, 0, 0, 0, 0, 0, -1, 1, 0, 0, 0, 0, 0;
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -1, 0;
     0, 0, 0, 0, 0, 0, 0, 1, 0, 0, -1, 0, 0, 0;
     0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 1, 0;
     0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 0, 0, 0;
     0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, -1, 0, 0;
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
     1, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
     -1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 0, 0, 1, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 0, 1, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0;
     0, -1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 1, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

def P6r : Matrix (Fin 14) (Fin 14) ℤ :=
  !![0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0;
     0, 0, 2, 0, 2, 0, -2, 0, 0, 0, -2, 0, 0, 0;
     2, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0;
     2, 0, 0, 0, 2, 0, -2, 0, -2, 0, 0, 0, 0, 0;
     2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0;
     2, 0, 2, 0, 0, 0, 0, 0, -2, 0, -2, 0, 0, 0;
     0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1;
     0, 1, 0, 1, 0, -1, 0, 1, 0, -1, 0, -1, 1, -1;
     0, 1, 0, -1, 0, 1, 0, -1, 0, -1, 0, 1, 1, -1;
     0, 1, 0, -1, 0, -1, 0, -1, 0, 1, 0, -1, 1, 1;
     0, -1, 0, 1, 0, 1, 0, -1, 0, 1, 0, -1, 1, -1;
     0, -1, 0, 1, 0, -1, 0, -1, 0, -1, 0, 1, 1, 1;
     0, -1, 0, -1, 0, 1, 0, 1, 0, -1, 0, -1, 1, 1;
     0, -1, 0, -1, 0, -1, 0, 1, 0, 1, 0, 1, 1, -1]

def P6i : Matrix (Fin 14) (Fin 14) ℤ :=
  !![0, 0, 2, 0, -2, 0, 2, 0, 0, 0, -2, 0, 0, 0;
     0, 0, -2, 0, 2, 0, 2, 0, 0, 0, -2, 0, 0, 0;
     -2, 0, 0, 0, 2, 0, -2, 0, 2, 0, 0, 0, 0, 0;
     2, 0, 0, 0, -2, 0, -2, 0, 2, 0, 0, 0, 0, 0;
     2, 0, -2, 0, 0, 0, 0, 0, -2, 0, 2, 0, 0, 0;
     -2, 0, 2, 0, 0, 0, 0, 0, -2, 0, 2, 0, 0, 0;
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

def Q6r : Matrix (Fin 14) (Fin 14) ℤ :=
  !![0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 0, 0, 0, 0, 0, 1, 1, 1, 1, -1, -1, -1, -1;
     2, 2, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 0, 0, 0, 0, 0, 1, 1, -1, -1, 1, 1, -1, -1;
     2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 0, 0, 0, 0, 0, 1, -1, 1, -1, 1, -1, 1, -1;
     2, -2, 2, -2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 0, 0, 0, 0, 0, 1, 1, -1, -1, -1, -1, 1, 1;
     0, 0, 2, -2, 2, -2, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 0, 0, 0, 0, 0, 1, -1, -1, 1, 1, -1, -1, 1;
     2, -2, 0, 0, 2, -2, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 0, 0, 0, 0, 0, 1, -1, 1, -1, -1, 1, -1, 1;
     0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1;
     0, 0, 0, 0, 0, 0, 1, -1, -1, 1, -1, 1, 1, -1]

def Q6i : Matrix (Fin 14) (Fin 14) ℤ :=
  !![0, 0, 2, -2, -2, 2, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
     -2, 2, 0, 0, 2, -2, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
     2, -2, -2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
     -2, -2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 0, -2, -2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
     2, 2, 0, 0, -2, -2, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

/-- Δ₆ in gauge (B). -/
def D6 : Matrix (Fin 14) (Fin 14) ℤ[i] := ofRI D6r D6i
/-- Change of basis: columns (B χ_S, 0), (0, χ_S) for |S| = 1, 2, then (0, χ_∅), (0, χ_{123}). -/
def P6 : Matrix (Fin 14) (Fin 14) ℤ[i] := ofRI P6r P6i
/-- `Q6 = P6ᴴ`. -/
def Q6 : Matrix (Fin 14) (Fin 14) ℤ[i] := ofRI Q6r Q6i

/-- Blocks over ℤ: six invariant planes (μ = 1, 1, 1, -1, -1, -1) and the two scalars 3, 9. -/
def blkq : Fin 7 → Matrix (Fin 2) (Fin 2) ℤ :=
  ![!![4, -1; -4, 5], !![4, -1; -4, 5], !![4, -1; -4, 5], !![4, -1; -4, 7], !![4, -1; -4, 7], !![4, -1; -4, 7],
    !![3, 0; 0, 9]]

def B6z : Matrix (Fin 14) (Fin 14) ℤ := Matrix.reindex e72 e72 (Matrix.blockDiagonal blkq)
def B6 : Matrix (Fin 14) (Fin 14) ℤ[i] := ofRI B6z 0

/-- Squared norms of the columns of `P6`. -/
def dvecz : Fin 14 → ℤ := ![32, 8, 32, 8, 32, 8, 32, 8, 32, 8, 32, 8, 8, 8]

/-! ## The two matrix identities, decided by the kernel on integer matrices -/

lemma D6P : D6 * P6 = P6 * B6 := by
  unfold D6 P6 B6
  rw [ofRI_mul, ofRI_mul]
  congr 1 <;> (simp only [Matrix.mul_zero, sub_zero, zero_add, ← Matrix.mulᵣ_eq]; decide +kernel)

lemma Q6P : Q6 * P6 = Matrix.diagonal (fun i => ((dvecz i : ℤ) : ℤ[i])) := by
  unfold Q6 P6
  rw [ofRI_mul, ofRI_diagonal]
  congr 1 <;> (simp only [← Matrix.mulᵣ_eq]; decide +kernel)

lemma dvec_ne_zero (i : Fin 14) : ((dvecz i : ℤ) : ℤ[i]) ≠ 0 := by
  rw [Int.cast_ne_zero]; fin_cases i <;> decide

/-! ## Characteristic polynomial of the block form -/

/-- Characteristic polynomial of an explicit 2 × 2 matrix over a commutative ring. -/
lemma cp2' {R : Type*} [CommRing R] [Nontrivial R] (a b c d : R) :
    (!![a, b; c, d] : Matrix (Fin 2) (Fin 2) R).charpoly = X ^ 2 - C (a + d) * X + C (a * d - b * c) := by
  rw [Matrix.charpoly_fin_two]
  simp [Matrix.trace_fin_two, Matrix.det_fin_two]

lemma blkq_mu1 (k : Fin 7) (hk : k = 0 ∨ k = 1 ∨ k = 2) : (blkq k).charpoly = X ^ 2 - 9 * X + 16 := by
  rcases hk with rfl | rfl | rfl <;>
  · rw [show blkq _ = !![4, -1; -4, 5] from rfl, cp2']; simp; try ring
lemma blkq_mu2 (k : Fin 7) (hk : k = 3 ∨ k = 4 ∨ k = 5) : (blkq k).charpoly = (X - 3) * (X - 8) := by
  rcases hk with rfl | rfl | rfl <;>
  · rw [show blkq _ = !![4, -1; -4, 7] from rfl, cp2']; simp; try ring
lemma blkq_6 : (blkq 6).charpoly = (X - 3) * (X - 9) := by
  rw [show blkq 6 = !![3, 0; 0, 9] from rfl, cp2']; simp; try ring

theorem charpoly_B6z :
    B6z.charpoly = (X - 9) * (X - 8) ^ 3 * (X - 3) ^ 4 * (X ^ 2 - 9 * X + 16) ^ 3 := by
  unfold B6z
  rw [Matrix.charpoly_reindex, charpoly_blockDiagonal, Fin.prod_univ_seven,
    blkq_mu1 0 (by simp), blkq_mu1 1 (by simp), blkq_mu1 2 (by simp),
    blkq_mu2 3 (by simp), blkq_mu2 4 (by simp), blkq_mu2 5 (by simp), blkq_6]
  ring

theorem charpoly_B6 :
    B6.charpoly = (X - 9) * (X - 8) ^ 3 * (X - 3) ^ 4 * (X ^ 2 - 9 * X + 16) ^ 3 := by
  unfold B6
  rw [ofRI_zero_eq_map, Matrix.charpoly_map, charpoly_B6z]
  simp

/-! ## Conjugation over the fraction field ℚ(i) and the pull-back -/

-- The fraction field of ℤ[i] (this is ℚ(i)); nothing is computed in it, it only hosts the conjugation argument.
abbrev Qi := FractionRing ℤ[i]
noncomputable def φ : ℤ[i] →+* Qi := algebraMap ℤ[i] Qi
lemma φ_inj : Function.Injective φ := IsFractionRing.injective ℤ[i] Qi

noncomputable def P' : Matrix (Fin 14) (Fin 14) Qi := P6.map φ
noncomputable def Pinv : Matrix (Fin 14) (Fin 14) Qi :=
  Matrix.diagonal (fun i => (φ ((dvecz i : ℤ) : ℤ[i]))⁻¹) * Q6.map φ

lemma Pinv_P : Pinv * P' = 1 := by
  unfold Pinv P'
  rw [Matrix.mul_assoc, ← Matrix.map_mul, Q6P, Matrix.diagonal_map (map_zero φ), Matrix.diagonal_mul_diagonal]
  ext i j
  simp only [Matrix.diagonal_apply, Matrix.one_apply]
  split_ifs with h
  · subst h; exact inv_mul_cancel₀ ((map_ne_zero_iff φ φ_inj).mpr (dvec_ne_zero i))
  · rfl

lemma P_Pinv : P' * Pinv = 1 := mul_eq_one_comm.mp Pinv_P

noncomputable def U6 : (Matrix (Fin 14) (Fin 14) Qi)ˣ := ⟨P', Pinv, P_Pinv, Pinv_P⟩

lemma D6_conj_K : D6.map φ = P' * B6.map φ * Pinv := by
  have h : D6.map φ * P' = P' * B6.map φ := by
    unfold P'; rw [← Matrix.map_mul, D6P, Matrix.map_mul]
  calc D6.map φ = D6.map φ * (P' * Pinv) := by rw [P_Pinv, Matrix.mul_one]
    _ = (D6.map φ * P') * Pinv := by rw [Matrix.mul_assoc]
    _ = P' * B6.map φ * Pinv := by rw [h]

/-- **Theorem 6.4 of the note, the quarter-flux case q = 6**: the spectrum of Δ₆ is
3 (×4), 8 (×3), 9 (×1) and the roots of x² - 9x + 16 (each ×3), as a statement over ℤ[i]. -/
theorem charpoly_D6 :
    D6.charpoly = (X - 9) * (X - 8) ^ 3 * (X - 3) ^ 4 * (X ^ 2 - 9 * X + 16) ^ 3 := by
  apply Polynomial.map_injective φ φ_inj
  rw [← Matrix.charpoly_map, D6_conj_K]
  have h := Matrix.charpoly_units_conj U6 (B6.map φ)
  rw [← Matrix.coe_units_inv] at h
  rw [show (↑U6 : Matrix (Fin 14) (Fin 14) Qi) = P' from rfl, show (↑U6⁻¹ : Matrix (Fin 14) (Fin 14) Qi) = Pinv from rfl] at h
  rw [h, Matrix.charpoly_map, charpoly_B6]

#print axioms charpoly_D6
